#ifndef IO_ERROR_H
#define IO_ERROR_H

namespace IO
{
	struct Error
	{
		enum class Type
		{
			NO_ERROR = 0,
			COORDINATE_UNDERSIZED,
			COORDINATE_OVERSIZED,
			INCONSCISTENT_COORDINATE_LEVEL,
			FEATURE_NEED_INITIALIZED_GEOMETRY,
			BAD_COORDINATE_FOR_GEMETRY,
			NEED_AT_LEAST_TWO_POSITION_FOR_LINESTRING,
			NEED_AT_LEAST_FOUR_POSITION_FOR_POLYGON,
			POLYGON_NEED_TO_BE_CLOSED,
			POLYGON_NEED_AT_LEAST_ONE_RING,
			UNKNOWN_GEOMETRY_TYPE,
			UNKNOWN_TYPE,
			UNEXPECTED_STATE_KEY,
			UNEXPECTED_STATE_VALUE,
			UNEXPECTED_STATE_OBJECT,
			UNEXPECTED_STATE_ARRAY,
			UNEXPECTED_PROPERTY_STATE,
			BBOX_SIZE_INCONSISTENT,
			PARSING_ERROR,
			FILE_OPENNING_FAILED,
			PROPERTY_KEY_ALREADY_EXIST,
		};
	};
}

#endif //IO_ERROR_H